//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInserter.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableToInsert
    {
        public int Id { get; set; }
        public string StringValue { get; set; }
        public Nullable<int> IntValue { get; set; }
    }
}
